name: prometheus to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: prometheus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
           
      - name: Print image tag
        run: echo $GITHUB_RUN_ID
        
         
      - name: 'Build and Push Image to ACR'
        uses: azure/docker-login@v1
        with:
         login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
         username: ${{ secrets.AZURE_REGISTRY_NAME }}
         password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      - run: |
         docker build prometheus -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/prometheus:${{ github.sha }}
         docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/prometheus:${{ github.sha }}
     
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: aks-atif
          cluster-name: azure-kubernetes-cluster-atif
          
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
         
         
      - uses: Azure/k8s-deploy@v1
        with:
         namespace: 'webapp'
         manifests: |
            prometheus-grafana-AKS/prometheus/kustomization/kustomization.yml
          
     
   
         login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
         username: ${{ secrets.AZURE_REGISTRY_NAME }}
         password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
         images: |
            ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/prometheus:${{ github.sha }}

